name: "MOU Release"
description: "Create a Github release with parsed commits into a given Markdown template"
author: "MindDoc Health GmbH"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  app:
    description: "The name of the app involved in the release"
    required: true
  commitDiffRef:
    description: >-
      The sha, branch or tag that will be used as base for git commit comparison.
      Branches should have the `heads/<branch name>` format and tags `tags/<tag name>`.
      The commits will be formatted into a Markdown list and replaced into the `$CHANGES` variable
      for the given `templatePath` template file.
    required: false
  draft:
    description: "Publish release draft"
    required: false
    default: "true"
  prerelease:
    description: "Mark release as prerelease when creating"
    required: false
    default: "true"
  releaseName:
    description: "Mark release as prerelease when creating"
    required: true
  releaseTag:
    description: "The git tag that belongs to the release"
    required: true
  templatePath:
    description: >-
      The path for the Markdown template that will be used to create the release body,
      relative to `.github/`.
    required: true
  token:
    description: "The token to access Github's API"
    required: true
runs:
  using: "node12"
  main: "dist/run.js"
